name: Deploy Django Static Files to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        working-directory: deintraumgarten
        run: |
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt

      - name: Collect Static Files
        working-directory: deintraumgarten
        run: |
          python manage.py collectstatic --noinput

      - name: Prepare Static Files and HTML
        run: |
          mkdir -p public
          if [ ! -f public/index.html ]; then
            cp deintraumgarten/myapp/templates/index.html public/index.html
          fi
          cp -r deintraumgarten/staticfiles/* public/

      - name: Upload Static Files
        uses: actions/upload-pages-artifact@v2
        with:
          path: public/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
