name: Deploy Django to GitHub Pages

on:
  push:
    branches:
      - main  # Führe den Workflow nur bei Änderungen im main-Branch aus

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout das Repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Installiere Python und Django
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 3. Collect static files (Django spezifisch)
      - name: Collect static files
        run: |
          python deintraumgarten/manage.py collectstatic --noinput

      # 4. Deploy statische Dateien zu GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}  # Hier wird der GitHub Token verwendet
          publish_dir: ./static  # Der Ordner, in dem collectstatic Dateien abgelegt werden
